### ISSUE TITLE
Explore Azure AI services

### ISSUE THREAD

**Issue by muthukumaranR** [NASA-IMPACT/LLM-cookbook-for-open-science#2]
# Description

Explore LLM and RAG services being offered by Azure AI setup within SMCE

# Goals
## 1. Create a azure openai endpoint and explore ways to UAC and token control
Steps:
- Create `azure AI studio`:
![image](https://github.com/NASA-IMPACT/smd-llm-workshop/assets/14973709/ab97a224-4fcf-48d4-8b9c-b46d04c117a3)
- Creates two resources: 
### 1. AI Project
- holds playground, flows (lambda like functions),  Evaluations, fine-tunings, Data sources, indexes, deployments. 
- Resources created using new AI project wizard:
![image](https://github.com/NASA-IMPACT/smd-llm-workshop/assets/14973709/ccbde13e-4e72-4c04-a6c2-5d328bf3a680)

- Most of the models only work on east-us-2. AI hub and project will need to be created on the location to access pay-as-you-go models.
- `AI hub` that does UAC, compute instances, connections, billing etc.

## 3. Deploy RAG application

```[tasklist]
### Tasks
- [ ] Create a azure openai endpoint and explore ways to UAC and token control
- [ ] Playground / chat interface options with pre loaded prompts
- [ ] Deploy RAG application
```
